version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py   # ← tells RTD your Sphinx config lives in docs/

python:
  install:
    - method: pip
      path: .                   # ← installs your package so autodoc can import it
    - requirements: docs/requirements.txt
